In [2]:
from urllib.request import urlopen
from urllib.error import HTTPError
from bs4 import BeautifulSoup
import requests

In [3]:
try:
    res = requests.get("https://www.worldometers.info/coronavirus/")
except HTTPError as e:
    print(e)

In [4]:
bs = BeautifulSoup(res.text)

In [5]:
print(bs.h1)

<h1>Coronavirus Cases:</h1>

In [6]:
print(bs.html.body.h1)

<h1>Coronavirus Cases:</h1>

In [7]:
tab = bs.findAll("table")

In [8]:
tab

[<table class="table table-bordered table-hover main_table_countries" id="main_table_countries_today" style="width:100%;margin-top: 0px !important;display:none;">
 <thead>
 <tr>
 <th width="1%">#</th>
 <th width="100">Country,<br>Other</br></th>
 <th width="20">Total<br>Cases</br></th>
 <th width="30">New<br>Cases</br></th>
 <th width="30">Total<br>Deaths</br></th>
 <th width="30">New<br>Deaths</br></th>
 <th width="30">Total<br>Recovered</br></th>
 <th width="30">New<br>Recovered</br></th>
 <th width="30">Active<br>Cases</br></th>
 <th width="30">Serious,<br>Critical</br></th>
 <th width="30">TotÂ Cases/<br/>1M pop</th>
 <th width="30">Deaths/<br/>1M pop</th>
 <th width="30">Total<br/>Tests</th>
 <th width="30">Tests/<br/>
 <nobr>1M pop</nobr>
 </th>
 <th width="30">Population</th>
 <th style="display:none" width="30">Continent</th>
 <th width="30">1 Case<br/>every X ppl</th><th width="30">1 Death<br/>every X ppl</th><th width="30">1 Test<br/>every X ppl</th>
 <th width="30">New Cases/1M pop</th>
 <th width="30">New Deaths/1M pop</th>
 <th width="30">Active Cases/1M pop</th>
 </tr>
 </thead>
 <tbody>
 <tr class="total_row_world row_continent" data-continent="North America" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>North America</nobr>
 </td>
 <td>130,847,105</td>
 <td></td>
 <td>1,669,358</td>
 <td></td>
 <td>126,303,659</td>
 <td></td>
 <td>2,874,088</td>
 <td>7,498</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="North America" style="display:none;">North America</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>
 <tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Asia</nobr>
 </td>
 <td>221,424,156</td>
 <td>+212</td>
 <td>1,552,739</td>
 <td>+1</td>
 <td>205,580,535</td>
 <td>+3,716</td>
 <td>14,290,882</td>
 <td>14,733</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Asia" style="display:none;">Asia</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>
 <tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Europe</nobr>
 </td>
 <td>253,047,410</td>
 <td>+1,860</td>
 <td>2,097,584</td>
 <td>+53</td>
 <td>248,352,260</td>
 <td>+1,759</td>
 <td>2,597,566</td>
 <td>4,559</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Europe" style="display:none;">Europe</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>
 <tr class="total_row_world row_continent" data-continent="South America" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>South America</nobr>
 </td>
 <td>69,652,726</td>
 <td></td>
 <td>1,364,920</td>
 <td></td>
 <td>66,628,557</td>
 <td></td>
 <td>1,659,249</td>
 <td>8,953</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="South America" style="display:none;">South America</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>
 <tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Oceania</nobr>
 </td>
 <td>14,751,199</td>
 <td>+907</td>
 <td>32,429</td>
 <td></td>
 <td>14,555,406</td>
 <td></td>
 <td>163,364</td>
 <td>46</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>
 <tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Africa</nobr>
 </td>
 <td>12,859,144</td>
 <td></td>
 <td>258,884</td>
 <td></td>
 <td>12,089,893</td>
 <td></td>
 <td>510,367</td>
 <td>529</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Africa" style="display:none;">Africa</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>
 <tr class="total_row_world row_continent" data-continent="" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr></nobr>
 </td>
 <td>721</td>
 <td></td>
 <td>15</td>
 <td></td>
 <td>706</td>
 <td></td>
 <td>0</td>
 <td>0</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="" style="display:none;"></td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>
 <tr class="total_row_world">
 <td></td>
 <td style="text-align:left;">World</td>
 <td>702,582,461</td>
 <td>+2,979</td>
 <td>6,975,929</td>
 <td>+54</td>
 <td>673,511,016</td>
 <td>+5,283</td>
 <td>22,095,516</td>
 <td>36,318</td>
 <td>90,135</td>
 <td>894.9</td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="all" style="display:none">All</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
 <td style="font-weight: bold; text-align:right">110,818,155</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">1,194,100                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">108,527,715</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">1,096,340</td>
 <td style="font-weight: bold; text-align:right">2,343</td>
 <td style="font-weight: bold; text-align:right">330,993</td>
 <td style="font-weight: bold; text-align:right">3,567</td>
 <td style="font-weight: bold; text-align:right">1,186,624,369</td>
 <td style="font-weight: bold; text-align:right">3,544,223</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">334,805,269</a> </td>
 <td data-continent="North America" style="display:none">North America</td>
 <!-- 1 Case/Death/Test every X -->
 <td>3</td><td>280</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">3,275</td>
 </tr>
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
 <td style="font-weight: bold; text-align:right">45,025,605</td>
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+160</td>
 <td style="font-weight: bold; text-align:right;">533,448                                </td>
 <td style="font-weight: bold;
                                     text-align:right;background-color:red; color:white">+1</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">N/A</td>
 <td style="text-align:right;font-weight:bold;">N/A</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">32,010</td>
 <td style="font-weight: bold; text-align:right">379</td>
 <td style="font-weight: bold; text-align:right">935,879,495</td>
 <td style="font-weight: bold; text-align:right">665,334</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,406,631,776</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <!-- 1 Case/Death/Test every X -->
 <td>31</td><td>2,637</td><td>2</td>
 <td style="font-weight: bold; text-align:right">0.1</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">1.0</td>
 </tr>
 <tr style="background-color:#F0F0F0">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
 <td style="font-weight: bold; text-align:right">40,138,560</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">167,642                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">39,970,918</span></td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">612,013</td>
 <td style="font-weight: bold; text-align:right">2,556</td>
 <td style="font-weight: bold; text-align:right">271,490,188</td>
 <td style="font-weight: bold; text-align:right">4,139,547</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,584,518</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>391</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 </tr>
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>
 <td style="font-weight: bold; text-align:right">38,808,771</td>
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+998</td>
 <td style="font-weight: bold; text-align:right;">181,845                                </td>
 <td style="font-weight: bold;
                                     text-align:right;background-color:red; color:white">+43</td>
 <td style="font-weight: bold; text-align:right">38,240,600</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">386,326</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">462,650</td>
 <td style="font-weight: bold; text-align:right">2,168</td>
 <td style="font-weight: bold; text-align:right">122,332,384</td>
 <td style="font-weight: bold; text-align:right">1,458,359</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">83,883,596</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>461</td><td>1</td>
 <td style="font-weight: bold; text-align:right">12</td>
 <td style="font-weight: bold; text-align:right">0.5</td>
 <td style="font-weight: bold; text-align:right">4,606</td>
 </tr>
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
 <td style="font-weight: bold; text-align:right">38,303,320</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">709,195                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">36,249,161</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">1,344,964</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">177,862</td>
 <td style="font-weight: bold; text-align:right">3,293</td>
 <td style="font-weight: bold; text-align:right">63,776,166</td>
 <td style="font-weight: bold; text-align:right">296,146</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">215,353,593</a> </td>
 <td data-continent="South America" style="display:none">South America</td>
 <!-- 1 Case/Death/Test every X -->
 <td>6</td><td>304</td><td>3</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">6,245</td>
 </tr>
 <tr style="background-color:#F0F0F0">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/south-korea/">S. Korea</a></td>
 <td style="font-weight: bold; text-align:right">34,571,873</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">35,934                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">34,535,939</span></td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">673,523</td>
 <td style="font-weight: bold; text-align:right">700</td>
 <td style="font-weight: bold; text-align:right">15,804,065</td>
 <td style="font-weight: bold; text-align:right">307,892</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/south-korea-population/">51,329,899</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <!-- 1 Case/Death/Test every X -->
 <td>1</td><td>1,428</td><td>3</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 </tr>
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/japan/">Japan</a></td>
 <td style="font-weight: bold; text-align:right">33,803,572</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">74,694                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right;">N/A</td>
 <td style="text-align:right;font-weight:bold;">N/A</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">269,169</td>
 <td style="font-weight: bold; text-align:right">595</td>
 <td style="font-weight: bold; text-align:right">100,414,883</td>
 <td style="font-weight: bold; text-align:right">799,578</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/japan-population/">125,584,838</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <!-- 1 Case/Death/Test every X -->
 <td>4</td><td>1,681</td><td>1</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">95,582</td>
 </tr>
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
 <td style="font-weight: bold; text-align:right">26,707,734</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">195,955                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">26,325,082</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">186,697</td>
 <td style="font-weight: bold; text-align:right">121</td>
 <td style="font-weight: bold; text-align:right">443,188</td>
 <td style="font-weight: bold; text-align:right">3,252</td>
 <td style="font-weight: bold; text-align:right">279,808,405</td>
 <td style="font-weight: bold; text-align:right">4,643,139</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,262,770</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>308</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">3,098</td>
 </tr>
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
 <td style="font-weight: bold; text-align:right">24,885,790</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">232,112                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">24,632,758</span></td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">20,920</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">363,307</td>
 <td style="font-weight: bold; text-align:right">3,389</td>
 <td style="font-weight: bold; text-align:right">522,526,476</td>
 <td style="font-weight: bold; text-align:right">7,628,357</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">68,497,907</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>3</td><td>295</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">305</td>
 </tr>
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
 <td style="font-weight: bold; text-align:right">23,875,738</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">401,945                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">23,294,406</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">179,387</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">163,750</td>
 <td style="font-weight: bold; text-align:right">2,757</td>
 <td style="font-weight: bold; text-align:right">273,400,000</td>

In [9]:
len(tab)

3

In [10]:
for name in tab:
    print(name.get_text())

#
Country,Other
TotalCases
NewCases
TotalDeaths
NewDeaths
TotalRecovered
NewRecovered
ActiveCases
Serious,Critical
TotÂ Cases/1M pop
Deaths/1M pop
TotalTests
Tests/
1M pop

Population
Continent
1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl
New Cases/1M pop
New Deaths/1M pop
Active Cases/1M pop






North America

130,847,105

1,669,358

126,303,659

2,874,088
7,498





North America














Asia

221,424,156
+212
1,552,739
+1
205,580,535
+3,716
14,290,882
14,733





Asia














Europe

253,047,410
+1,860
2,097,584
+53
248,352,260
+1,759
2,597,566
4,559





Europe














South America

69,652,726

1,364,920

66,628,557

1,659,249
8,953





South America














Oceania

14,751,199
+907
32,429

14,555,406

163,364
46





Australia/Oceania














Africa

12,859,144

258,884

12,089,893

510,367
529





Africa
















721

15

706

0
0



















World
702,582,461
+2,979
6,975,929
+54
673,511,016
+5,283
22,095,516
36,318
90,135
894.9



All












1
USA
110,818,155

1,194,100

108,527,715

1,096,340
2,343
330,993
3,567
1,186,624,369
3,544,223
334,805,269
North America

32800


3,275


2
India
45,025,605
+160
533,448
+1
N/A
N/A
N/A
N/A
32,010
379
935,879,495
665,334
1,406,631,776
Asia

312,6372
0.1

1.0


3
France
40,138,560

167,642

39,970,918

0

612,013
2,556
271,490,188
4,139,547
65,584,518
Europe

23910





4
Germany
38,808,771
+998
181,845
+43
38,240,600

386,326
N/A
462,650
2,168
122,332,384
1,458,359
83,883,596
Europe

24611
12
0.5
4,606


5
Brazil
38,303,320

709,195

36,249,161

1,344,964
N/A
177,862
3,293
63,776,166
296,146
215,353,593
South America

63043


6,245


6
S. Korea
34,571,873

35,934

34,535,939

0

673,523
700
15,804,065
307,892
51,329,899
Asia

11,4283





7
Japan
33,803,572

74,694

N/A
N/A
N/A
N/A
269,169
595
100,414,883
799,578
125,584,838
Asia

41,6811


95,582


8
Italy
26,707,734

195,955

26,325,082

186,697
121
443,188
3,252
279,808,405
4,643,139
60,262,770
Europe

23080


3,098


9
UK
24,885,790

232,112

24,632,758

20,920
N/A
363,307
3,389
522,526,476
7,628,357
68,497,907
Europe

32950


305


10
Russia
23,875,738

401,945

23,294,406

179,387
N/A
163,750
2,757
273,400,000
1,875,095
145,805,947
Europe

63631


1,230


11
Turkey
17,232,066

102,174

N/A
N/A
N/A
N/A
201,399
1,194
162,743,369
1,902,052
85,561,976
Asia

58371


4,024


12
Spain
13,914,811

121,760

13,762,417

30,634
231
297,840
2,606
471,036,328
10,082,298
46,719,142
Europe

33840


656


13
Australia
11,754,909
+907
24,073

N/A
N/A
N/A
18
450,919
923
81,916,639
3,142,326
26,068,792
Australia/Oceania

21,0830
35

2,274


14
Vietnam
11,624,114

43,206

10,640,971

939,937

117,470
437
85,826,548
867,342
98,953,541
Asia

92,2901


9,499


15
Taiwan
10,241,523

19,005

10,222,518

0

428,720
796
30,742,304
1,286,903
23,888,595
Asia

21,2571





16
Argentina
10,081,076

130,699

9,949,347

1,030

219,105
2,841
35,716,069
776,264
46,010,234
South America

53521


22


17
Netherlands
8,633,235

22,992

8,608,038

2,205
N/A
501,598
1,336
25,984,435
1,509,718
17,211,447
Europe

27491


128


18
Mexico
7,702,809

334,958

6,899,865

467,986
N/A
58,549
2,546
20,013,810
152,124
131,562,772
North America

173937


3,557


19
Iran
7,625,812

146,767

N/A
N/A
N/A

88,649
1,706
57,320,267
666,338
86,022,837
Asia

115862


1,184


20
Indonesia
6,826,664

161,954

6,647,104

17,606
N/A
24,457
580
114,158,919
408,975
279,134,505
Asia

411,7242


63


21
Poland
6,654,829
+429
120,487
+8
N/A
N/A
N/A
N/A
176,335
3,193
39,202,134
1,038,748
37,739,785
Europe

63131
11
0.2
31,754


22
Colombia
6,390,565

143,138

6,209,477

37,950
342
124,058
2,779
36,951,507
717,327
51,512,762
South America

83601


737


23
Greece
6,101,379

37,869

N/A
N/A
N/A

591,412
3,671
102,228,365
9,909,078
10,316,637
Europe

22720





24
Austria
6,081,287

22,542

6,054,934

3,811

670,727
2,486
211,273,524
23,302,116
9,066,710
Europe

14020


420


25
Portugal
5,641,679

28,060

5,611,411

2,208
61
556,347
2,767
46,139,518
4,549,993
10,140,570
Europe

23610


218


26
Ukraine
5,557,995

112,418

5,445,577

0

128,681
2,603
32,603,805
754,855
43,192,122
Europe

83841





27
Chile
5,345,980

64,497

5,252,450

29,033
7
277,710
3,350
50,382,097
2,617,225
19,250,195
South America

42980


1,508


28
Malaysia
5,269,967

37,340

5,220,707

11,920
11
158,824
1,125
68,580,916
2,066,869
33,181,072
Asia

68890


359


29
Canada
4,915,977

57,905

4,823,167

34,905
99
128,059
1,508
66,572,774
1,734,189
38,388,419
North America

86631


909


30
Belgium
4,856,459

34,376

4,815,315
+726
6,768
N/A
416,210
2,946
37,454,182
3,209,915
11,668,278
Europe

23390


580


31
Israel
4,841,772

12,707

4,798,473

30,592
N/A
519,169
1,363
41,373,364
4,436,346
9,326,000
Asia

27340


3,280


32
DPRK
4,772,813

74

4,772,739

0

183,636
3


25,990,679
Asia

5351,225





33
Thailand
4,765,003

34,547

4,692,636

37,820
N/A
67,996
493
17,270,775
246,450
70,078,203
Asia

152,0284


540


34
Czechia
4,756,789
+157
43,482

4,709,179
+88
4,128
12
443,037
4,050
57,722,189
5,376,115
10,736,784
Europe

22470
15

384


35
Peru
4,568,225

222,161

4,346,064

0
4
135,619
6,595
39,010,194
1,158,115
33,684,208
South America

71521





36
Switzerland
4,449,493

14,452

4,432,506

2,535
N/A
507,144
1,647
23,833,472
2,716,487
8,773,637
Europe

26070


289


37
Philippines
4,140,383

66,864

4,067,381

6,138
N/A
36,800
594
36,102,746
320,888
112,508,994
Asia

271,6833


55


38
South Africa
4,076,463

102,595

3,912,506

61,362
192
67,095
1,689
26,795,090
441,027
60,756,135
Africa

155922


1,010


39
Romania
3,521,283

68,822

3,446,072

6,389
16
185,026
3,616
28,559,175
1,500,640
19,031,335
Europe

52771


336


40
Denmark
3,183,756

8,814

3,174,942

0

545,636
1,511
129,333,107
22,165,247
5,834,950
Europe

26620





41
Singapore
2,994,295

1,933

2,975,782
+3,484
16,580
4
503,789
325
24,756,666
4,165,302
5,943,546
Asia

23,0750


2,790


42
Hong Kong
2,926,873

14,464

2,910,211

2,198
N/A
384,897
1,902
76,127,725
10,011,143
7,604,299
Asia

35260


289


43
Sweden
2,752,056

27,142

2,722,311
+145
2,603
N/A
269,309
2,656
19,500,873
1,908,301
10,218,971
Europe

43771


255


44
Serbia
2,612,780

18,057

2,593,302

1,421

301,950
2,087
13,390,135
1,547,453
8,653,016
Europe

34791


164


45
New Zealand
2,574,813

5,452

2,565,293

4,068

525,665
1,113
7,768,604
1,586,011
4,898,203
Australia/Oceania

28981


831


46
Iraq
2,465,545

25,375

2,439,497

673

58,474
602
19,544,451
463,523
42,164,965
Asia

171,6622


16


47
Hungary
2,229,267

49,013

2,152,155

28,099

232,064
5,102
11,394,556
1,186,160
9,606,259
Europe

41961


2,925


48
Bangladesh
2,047,199
+49
29,482

N/A
N/A
N/A
N/A
12,194
176
15,254,399
90,862
167,885,689
Asia

825,69511
0.3

20


49
Slovakia
1,876,826

21,212

1,855,234

380
23
343,729
3,885
7,448,789
1,364,199
5,460,193
Europe

32571


70


50
Georgia
1,855,289

17,132

N/A
N/A
N/A

467,476
4,317
16,920,079
4,263,340
3,968,738
Asia

22320


15,524


51
Jordan
1,746,997

14,122

1,731,007

1,868
59
169,597
1,371
17,201,885
1,669,945
10,300,869
Asia

67291


181


52
Ireland
1,732,701

9,474

1,720,703

2,524
19
345,146
1,887
13,083,449
2,606,161
5,020,199
Europe

35300


503


53
Pakistan
1,581,936

30,664

1,538,689

12,583

6,893
134
30,589,153
133,292
229,488,994
Asia

1457,4848


55


54
Finland
1,514,669

11,935

1,502,184
+185
550
N/A
272,670
2,149
12,108,977
2,179,850
5,554,960
Europe

44650


99


55
Norway
1,509,374
+45
5,732

1,502,873
+83
769
N/A
273,865
1,040
11,002,430
1,996,315
5,511,370
Europe

49621
8

140


56
Kazakhstan
1,411,831

13,848

1,383,020

14,963
24
73,514
721
11,575,012
602,707
19,205,043
Asia

141,3872


779


57
Lithuania
1,394,124
+149
9,889

1,380,558
+293
3,677
N/A
523,770
3,715
10,540,357
3,959,997
2,661,708
Europe

22690
56

1,381


58
Slovenia
1,356,189
+15
7,100

1,348,826
+118
263
N/A
652,631
3,417
2,847,701
1,370,382
2,078,034
Europe

22931
7

127


59
Bulgaria
1,338,621
+67
38,731
+2
1,292,087
+121
7,803
24
195,573
5,659
11,588,937
1,693,151
6,844,597
Europe

51771
10
0.3
1,140


60
Croatia
1,309,728

18,687

1,258,432

32,609

322,650
4,604
5,660,084
1,394,355
4,059,286
Europe

32171


8,033


61
Guatemala
1,284,003

20,278

1,261,824

1,901
5
69,092
1,091
7,593,848
408,622
18,584,039
North America

149162


102


62
Morocco
1,278,512

16,301

N/A
N/A
N/A
N/A
33,847
432
13,001,033
344,191
37,772,756
Africa

302,3173


160


63
Lebanon
1,243,838

10,952

1,087,587

145,299
74
186,068
1,638
4,795,578
717,380
6,684,849
Asia

56101


21,736


64
Costa Rica
1,238,883

9,428

N/A
N/A
N/A
N/A
239,058
1,819
4,659,757
899,158
5,182,354
North America

45501


71,154


65
Bolivia
1,211,716

22,407

1,177,145

12,164
220
101,038
1,868
2,710,261
225,993
11,992,656
South America

105354


1,014


66
Tunisia
1,153,361

29,423

N/A
N/A
N/A
N/A
95,741
2,442
5,013,383
416,164
12,046,656
Africa

104092


1,157


67
Cuba
1,115,210

8,530

1,106,613

67

98,642
754
14,398,718
1,273,586
11,305,652
North America

101,3251


6


68
Ecuador
1,070,188

36,043

1,034,145

0

59,083
1,990
3,082,403
170,173
18,113,361
South America

175036





69
UAE
1,067,030

2,349

N/A
N/A
N/A

105,837
233
200,732,262
19,910,389
10,081,785
Asia

94,2920


1,007


70
Panama
1,058,933

8,688

1,044,922

5,323
16
238,125
1,954
7,847,296
1,764,641
4,446,964
North America

45121


1,197


71
Uruguay
1,041,111

7,664

1,030,944

2,503
18
297,799
2,192
6,114,822
1,749,083
3,496,016
South America

34561


716


72
Mongolia
1,011,451

2,284

1,009,159

8
N/A
299,416
676
4,030,048
1,193,000
3,378,078
Asia

31,4791


2


73
Nepal
1,003,450

12,031

991,322

97

33,199
398
6,047,766
200,088
30,225,582
Asia

302,5125


3


74
Belarus
994,037

7,118

985,592

1,327

105,381
755
13,646,641
1,446,722
9,432,800
Europe

91,3251


141


75
Latvia
982,075

6,653

971,406

4,016

531,185
3,598
7,885,792
4,265,272
1,848,837
Europe

22780


2,172


76
Saudi Arabia
841,469

9,646

N/A
N/A
N/A

23,475
269
45,481,735
1,268,848
35,844,909
Asia

433,7161


109


77
Azerbaijan
834,371

10,379

823,872

120

81,005
1,008
7,733,717
750,831
10,300,205
Asia

129921


12


78
Paraguay
831,154

20,132

N/A
N/A
N/A
N/A
113,766
2,756
2,657,506
363,751
7,305,843
South America

93633


15,427


79
Bahrain
729,549

1,574

727,915

60
N/A
408,944
882
10,948,549
6,137,138
1,783,983
Asia

21,1330


34


80
Cyprus
681,110

1,365

679,745

0

556,741
1,116
9,640,118
7,879,860
1,223,387
Asia

28960





81
Dominican Republic
674,608

4,384

669,198

1,026
4
61,015
397
3,740,928
338,350
11,056,370
North America

162,5223


93


82
Sri Lanka
672,745

16,896

655,847

2

31,180
783
6,486,117
300,619
21,575,842
Asia

321,2773


0.09


83
Kuwait
666,756

2,570

N/A
N/A
N/A

152,216
587
8,455,743
1,930,391
4,380,326
Asia

71,7041


902


84
Myanmar
641,687

19,495

620,159

2,033

11,619
353
11,614,900
210,311
55,227,143
Asia

862,8335


37


85
Moldova
633,184

12,190

N/A
N/A
N/A
N/A
157,776
3,037
3,216,305
801,437
4,013,171
Europe

63291


29,117


86
Estonia
627,452

3,001

N/A
N/A
N/A
N/A
474,656
2,270
6,923,640
5,237,603
1,321,910
Europe

24400


75,240


87
Palestine
621,008

5,404

615,445

159

116,173
1,011
3,078,533
575,907
5,345,541
Asia

99892


30


88
Venezuela
552,695

5,856

546,537

302
31
18,885
200
3,359,014
114,771
29,266,991
South America

534,9989


10


89
Egypt
516,023

24,613

442,182

49,228
122
4,861
232
3,693,367
34,792
106,156,692
Africa

2064,31329


464


90
Qatar
514,524

690

513,687

147
16
172,664
232
4,065,369
1,364,257
2,979,915
Asia

64,3191


49


91
Libya
507,274

6,437

500,835

2

72,048
914
2,483,848
352,782
7,040,745
Africa

141,0943


0.3


92
Ethiopia
501,117

7,574

488,171

5,372

4,148
63
5,565,340
46,066
120,812,698
Africa

24115,95122


44


93
RÃ©union
494,595

921

N/A
N/A
N/A
N/A
544,672
1,014
1,603,660
1,766,027
908,061
Africa

29861


82,706


94
Honduras
474,590

11,165

N/A
N/A
N/A
N/A
46,432
1,092
1,660,662
162,472
10,221,247
North America

229156


32,372


95
Armenia
451,426

8,776

435,162

7,488

151,895
2,953
3,242,901
1,091,164
2,971,966
Asia

73391


2,520


96
Bosnia and Herzegovina
403,558

16,382

379,084

8,092

124,198
5,042
1,884,721
580,036
3,249,317
Europe

81982


2,490


97
Oman
399,449

4,628

N/A
N/A
N/A

75,028
869
25,000,000
4,695,724
5,323,993
Asia

131,1500


1,907


98
Luxembourg
390,615

1,232

N/A
N/A
N/A

608,083
1,918
4,587,145
7,140,959
642,371
Europe

25210


113,164


99
North Macedonia
350,244

9,963

337,068

3,213

168,281
4,787
2,226,216
1,069,626
2,081,304
Europe

62091


1,544


100
Zambia
349,304

4,069

341,316

3,919

17,940
209
4,112,961
211,244
19,470,234
Africa

564,7855


201


101
Kenya
344,130

5,689

337,309

1,132
N/A
6,122
101
3,967,062
70,569
56,215,221
Africa

1639,88114


20


102
Brunei
338,569

225

243,601

94,743
3
760,093
505
717,784
1,611,437
445,431
Asia

11,9801


212,700


103
Albania
334,818

3,605

330,233

980

116,809
1,258
1,941,032
677,173
2,866,374
Europe

97951


342


104
Botswana
330,442

2,801

327,049

592
1
135,363
1,147
2,026,898
830,300
2,441,162
Africa

78721


243


105
Montenegro
296,386

2,845

291,794

1,747
N/A
471,990
4,531
2,769,281
4,410,034
627,950
Europe

22210


2,782


106
Algeria
272,010

6,881

183,061

82,068

5,998
152
230,960
5,093
45,350,148
Africa

1676,591196


1,810


107
Nigeria
267,173

3,155

259,953

4,065
11
1,233
15
5,708,974
26,339
216,746,934
Africa

81168,70038


19


108
Zimbabwe
266,257

5,737

258,888

1,632
12
17,367
374
2,525,756
164,744
15,331,428
Africa

582,6726


106


109
Uzbekistan
253,662

1,637

241,486

10,539
23
7,378
48
1,377,915
40,077
34,382,084
Asia

13621,00325


307


110
Mozambique
233,731

2,250

228,805

2,676
11
7,064
68
1,371,127
41,437
33,089,461
Africa

14214,70624


81


111
Afghanistan
231,010

7,980

209,662

13,368

5,668
196
1,352,598
33,189
40,754,388
Asia

1765,10730


328


112
Martinique
230,354

1,102

N/A
N/A
N/A
N/A
615,777
2,946
828,928
2,215,870
374,087
North America

23390


612,553


113
Laos
218,916
+1
758

N/A
N/A
N/A

29,263
101
1,233,207
164,845
7,481,023
Asia

349,8696
0.1

28,138


114
Iceland
209,870

229

N/A
N/A
N/A

607,627
663
1,996,384
5,780,036
345,393
Europe

21,5080


387,836


115
Kyrgyzstan
206,897

2,991

196,406

7,500
131
30,750
445
1,907,195
283,460
6,728,271
Asia

332,2504


1,115


116
Guadeloupe
203,235

1,021

N/A
N/A
N/A
N/A
508,349
2,554
938,039
2,346,306
399,794
North America

23920


500,168


117
El Salvador
201,855

4,230

179,410

18,215

30,816
646
2,610,114
398,467
6,550,389
North America

321,5493


2,781


118
Trinidad and Tobago
191,496

4,390

187,078

28
N/A
136,143
3,121
913,289
649,295
1,406,585
North America

73202


20


119
Maldives
186,694

316

163,687

22,691
25
345,100
584
2,213,831
4,092,223
540,985
Asia

31,7120


41,944


120
Namibia
172,256

4,103

167,099

1,054

65,400
1,558
1,062,663
403,460
2,633,874
Africa

156422


400


121
Uganda
171,983

3,632

100,431

67,920

3,551
75
3,012,408
62,198
48,432,863
Africa

28213,33516


1,402


122
Ghana
171,889

1,462

170,425

2

5,306
45
2,541,625
78,456
32,395,450
Africa

18822,15813


0.06


123
Jamaica
156,739

3,739

N/A
N/A
N/A

52,507
1,253
1,183,986
396,633
2,985,094
North America

197983


16,674


124
Cambodia
139,085
+2
3,056

136,015
+3
14

8,101
178
3,091,420
180,062
17,168,639
Asia

1235,6186
0.1

0.8


125
Rwanda
133,518

1,468

132,039

11

9,817
108
6,021,981
442,778
13,600,464
Africa

1029,2652


0.8


126
Cameroon
125,248

1,974

123,273

1
N/A
4,487
71
1,751,774
62,762
27,911,548
Africa

22314,14016


0.04


127
Malta
121,334

882

119,972

480

273,254
1,986
2,165,394
4,876,651
444,033
Europe

45030


1,081


128
Barbados
110,480

648

108,647

1,185

383,580
2,250
813,173
2,823,292
288,023
North America

34440


4,114


129
Angola
107,271

1,937

103,419

1,915

3,062
55
1,499,795
42,818
35,027,343
Africa

32718,08323


55


130
Channel Islands
101,717

228

101,321

168

576,421
1,292
1,252,808
7,099,551
176,463
Europe

27740


952


131
DRC
99,338

1,468

84,489

13,381

1,043
15
846,704
8,890
95,240,792
Africa

95964,878112


140


132
French Guiana
98,041

420

11,254

86,367
6
312,065
1,337
651,257
2,072,951
314,169
South America

37480


274,906


133
Malawi
89,168

2,686

N/A
N/A
N/A
N/A
4,418
133
624,784
30,959
20,180,839
Africa

2267,51332


41


134
Senegal
89,053

1,971

87,024

58

5,044
112
1,146,543
64,946
17,653,671
Africa

1988,95715


3


135
Ivory Coast
88,384

835

87,497

52

3,186
30
1,690,934
60,951
27,742,298
Africa

31433,22416


2


136
Suriname
82,588

1,408

N/A
N/A
N/A

138,378
2,359
242,207
405,822
596,831
South America

74242


52,623


137
New Caledonia
80,064

314

N/A
N/A
N/A
N/A
275,214
1,079
98,964
340,182
290,915
Australia/Oceania

49263


498


138
French Polynesia
79,254

650

N/A
N/A
N/A
N/A
278,902
2,287


284,164
Australia/Oceania

4437


158,725


139
Eswatini
75,191

1,427

73,116

648

63,462
1,204
1,048,704
885,119
1,184,817
Africa

168301


547


140
Guyana
74,137

1,300

72,013

824

93,366
1,637
733,218
923,396
794,045
South America

116111


1,038


141
Belize
71,373

688

N/A
N/A
N/A
N/A
173,156
1,669
576,016
1,397,453
412,190
North America

65991


1,456


142
Fiji
69,117

885

67,226

1,006

75,997
973
672,883
739,866
909,466
Australia/Oceania

131,0281


1,106


143
Madagascar
68,486

1,426

66,862

198

2,347
49
531,329
18,210
29,178,077
Africa

42620,46155


7


144
Cabo Verde
64,477

417

63,755

305
23
113,580
735
401,622
707,482
567,678
Africa

91,3611


537


145
Sudan
63,993

5,046

58,947

0

1,391
110
562,941
12,240
45,992,020
Africa

7199,11582





146
Mauritania
63,808

997

62,471

340

13,017
203
1,009,957
206,030
4,901,981
Africa

774,9175


69


147
Bhutan
62,697

21

61,564

1,112

79,571
27
2,303,734
2,923,739
787,941
Asia

1337,5210


1,411


148
Syria
57,743

3,165

54,578

0

2,982
163
146,269
7,553
19,364,809
Asia

3356,118132





149
Burundi
54,721

38

53,569

1,114

4,334
3
345,742
27,386
12,624,840
Africa

231332,23337


88


150
Seychelles
51,220

172

51,048

0

515,157
1,730


99,426
Africa

2578





151
Gabon
49,051

307

48,674

70

21,038
132
1,621,909
695,641
2,331,533
Africa

487,5951


30


152
Andorra
48,015

165

N/A
N/A
N/A
N/A
619,844
2,130
249,838
3,225,256
77,463
Europe

24690


3,705


153
Papua New Guinea
46,864

670

46,168

26
N/A
5,043
72
249,149
26,813
9,292,169
Australia/Oceania

19813,86937


3


154
CuraÃ§ao
45,986

295

44,720

971
3
277,812
1,782
496,693
3,000,640
165,529
North America

45610


5,866


155
Aruba
44,224

292

42,438

1,494
2
410,969
2,714
177,885
1,653,068
107,609
North America

23691


13,884


156
Tanzania
43,223

846

N/A
N/A
N/A
N/A
683
13


63,298,550
Africa

1,46474,821


667


157
Mauritius
43,025

1,051

41,278

696

33,752
824
358,675
281,374
1,274,727
Africa

301,2134


546


158
Mayotte
42,027

188

N/A
N/A
N/A

146,815
657
176,919
618,038
286,259
Africa

71,5232


135,804


159
Togo
39,553

290

39,263

0

4,556
33
812,881
93,641
8,680,837
Africa

21929,93411





160
Guinea
38,572

468

37,757

347
N/A
2,782
34
660,107
47,607
13,865,691
Africa

35929,62821


25


161
Bahamas
38,084

844

36,366

874
1
95,087
2,107
257,839
643,767
400,516
North America

114752


2,182


162
Isle of Man
38,008

116

N/A
N/A
N/A

443,335
1,353
150,753
1,758,422
85,732
Europe

27391


129,450


163
Lesotho
36,135

723

25,980

9,432

16,608
332
431,221
198,199
2,175,699
Africa

603,0095


4,335


164
Faeroe Islands
34,658

28

N/A
N/A
N/A
N/A
703,959
569
778,000
15,802,409
49,233
Europe

11,7580


547,133


165
Haiti
34,542

860

33,576

106

2,957
74
132,422
11,337
11,680,283
North America

33813,58288


9


166
Mali
33,164

743

32,332

89

1,544
35
804,909
37,483
21,473,764
Africa

64828,90127


4


167
Cayman Islands
31,472

37

8,553

22,882
1
467,797
550
222,773
3,311,280
67,277
North America

21,8180


340,116


168
Saint Lucia
30,209

410

29,799

0

163,192
2,215
210,983
1,139,752
185,113
North America

64511






In [11]:
tab1 = bs.findAll({"tr"})

In [12]:
len(tab1)

744

In [13]:
tab1[0]

<tr>
<th width="1%">#</th>
<th width="100">Country,<br>Other</br></th>
<th width="20">Total<br>Cases</br></th>
<th width="30">New<br>Cases</br></th>
<th width="30">Total<br>Deaths</br></th>
<th width="30">New<br>Deaths</br></th>
<th width="30">Total<br>Recovered</br></th>
<th width="30">New<br>Recovered</br></th>
<th width="30">Active<br>Cases</br></th>
<th width="30">Serious,<br>Critical</br></th>
<th width="30">TotÂ Cases/<br/>1M pop</th>
<th width="30">Deaths/<br/>1M pop</th>
<th width="30">Total<br/>Tests</th>
<th width="30">Tests/<br/>
<nobr>1M pop</nobr>
</th>
<th width="30">Population</th>
<th style="display:none" width="30">Continent</th>
<th width="30">1 Case<br/>every X ppl</th><th width="30">1 Death<br/>every X ppl</th><th width="30">1 Test<br/>every X ppl</th>
<th width="30">New Cases/1M pop</th>
<th width="30">New Deaths/1M pop</th>
<th width="30">Active Cases/1M pop</th>
</tr>

In [14]:
tab1[9].findAll({"td"})[1].get_text()

'USA'

In [15]:
country = tab1[0].findAll({"th"})[1].get_text()

In [16]:
country

'Country,Other'

In [17]:
totalCases = tab1[0].findAll({"th"})[2].get_text()

In [18]:
totalCases

'TotalCases'

In [19]:
totalDeaths = tab1[0].findAll({"th"})[4].get_text()

In [20]:
totalDeaths

'TotalDeaths'

In [21]:
rows = [country,totalCases,totalDeaths]

In [22]:
rows

['Country,Other', 'TotalCases', 'TotalDeaths']

In [23]:
for result in tab1:
    data = result.findAll('td')

In [24]:
len(data)

22

In [25]:
data

[<td></td>,
 <td><strong>Total:</strong></td>,
 <td>702,566,459</td>,
 <td style="background-color:#FFEEAA; color:#000;">+39,491</td>,
 <td>6,975,759</td>,
 <td style="background-color:red; color:#fff">+268</td>,
 <td>673,463,183</td>,
 <td style="background-color:#c8e6c9; color:#000">+48,383</td>,
 <td>22,127,517</td>,
 <td>36,399</td>,
 <td>90,132.7</td>,
 <td>894.9</td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td data-continent="all" style="display:none">All</td>,
 <td>
 </td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td></td>]

In [26]:
tab1

[<tr>
 <th width="1%">#</th>
 <th width="100">Country,<br>Other</br></th>
 <th width="20">Total<br>Cases</br></th>
 <th width="30">New<br>Cases</br></th>
 <th width="30">Total<br>Deaths</br></th>
 <th width="30">New<br>Deaths</br></th>
 <th width="30">Total<br>Recovered</br></th>
 <th width="30">New<br>Recovered</br></th>
 <th width="30">Active<br>Cases</br></th>
 <th width="30">Serious,<br>Critical</br></th>
 <th width="30">TotÂ Cases/<br/>1M pop</th>
 <th width="30">Deaths/<br/>1M pop</th>
 <th width="30">Total<br/>Tests</th>
 <th width="30">Tests/<br/>
 <nobr>1M pop</nobr>
 </th>
 <th width="30">Population</th>
 <th style="display:none" width="30">Continent</th>
 <th width="30">1 Case<br/>every X ppl</th><th width="30">1 Death<br/>every X ppl</th><th width="30">1 Test<br/>every X ppl</th>
 <th width="30">New Cases/1M pop</th>
 <th width="30">New Deaths/1M pop</th>
 <th width="30">Active Cases/1M pop</th>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="North America" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>North America</nobr>
 </td>
 <td>130,847,105</td>
 <td></td>
 <td>1,669,358</td>
 <td></td>
 <td>126,303,659</td>
 <td></td>
 <td>2,874,088</td>
 <td>7,498</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="North America" style="display:none;">North America</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Asia</nobr>
 </td>
 <td>221,424,156</td>
 <td>+212</td>
 <td>1,552,739</td>
 <td>+1</td>
 <td>205,580,535</td>
 <td>+3,716</td>
 <td>14,290,882</td>
 <td>14,733</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Asia" style="display:none;">Asia</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Europe</nobr>
 </td>
 <td>253,047,410</td>
 <td>+1,860</td>
 <td>2,097,584</td>
 <td>+53</td>
 <td>248,352,260</td>
 <td>+1,759</td>
 <td>2,597,566</td>
 <td>4,559</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Europe" style="display:none;">Europe</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="South America" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>South America</nobr>
 </td>
 <td>69,652,726</td>
 <td></td>
 <td>1,364,920</td>
 <td></td>
 <td>66,628,557</td>
 <td></td>
 <td>1,659,249</td>
 <td>8,953</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="South America" style="display:none;">South America</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Oceania</nobr>
 </td>
 <td>14,751,199</td>
 <td>+907</td>
 <td>32,429</td>
 <td></td>
 <td>14,555,406</td>
 <td></td>
 <td>163,364</td>
 <td>46</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Africa</nobr>
 </td>
 <td>12,859,144</td>
 <td></td>
 <td>258,884</td>
 <td></td>
 <td>12,089,893</td>
 <td></td>
 <td>510,367</td>
 <td>529</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Africa" style="display:none;">Africa</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr></nobr>
 </td>
 <td>721</td>
 <td></td>
 <td>15</td>
 <td></td>
 <td>706</td>
 <td></td>
 <td>0</td>
 <td>0</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="" style="display:none;"></td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world">
 <td></td>
 <td style="text-align:left;">World</td>
 <td>702,582,461</td>
 <td>+2,979</td>
 <td>6,975,929</td>
 <td>+54</td>
 <td>673,511,016</td>
 <td>+5,283</td>
 <td>22,095,516</td>
 <td>36,318</td>
 <td>90,135</td>
 <td>894.9</td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="all" style="display:none">All</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
 <td style="font-weight: bold; text-align:right">110,818,155</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">1,194,100                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">108,527,715</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">1,096,340</td>
 <td style="font-weight: bold; text-align:right">2,343</td>
 <td style="font-weight: bold; text-align:right">330,993</td>
 <td style="font-weight: bold; text-align:right">3,567</td>
 <td style="font-weight: bold; text-align:right">1,186,624,369</td>
 <td style="font-weight: bold; text-align:right">3,544,223</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">334,805,269</a> </td>
 <td data-continent="North America" style="display:none">North America</td>
 <!-- 1 Case/Death/Test every X -->
 <td>3</td><td>280</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">3,275</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
 <td style="font-weight: bold; text-align:right">45,025,605</td>
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+160</td>
 <td style="font-weight: bold; text-align:right;">533,448                                </td>
 <td style="font-weight: bold;
                                     text-align:right;background-color:red; color:white">+1</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">N/A</td>
 <td style="text-align:right;font-weight:bold;">N/A</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">32,010</td>
 <td style="font-weight: bold; text-align:right">379</td>
 <td style="font-weight: bold; text-align:right">935,879,495</td>
 <td style="font-weight: bold; text-align:right">665,334</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,406,631,776</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <!-- 1 Case/Death/Test every X -->
 <td>31</td><td>2,637</td><td>2</td>
 <td style="font-weight: bold; text-align:right">0.1</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">1.0</td>
 </tr>,
 <tr style="background-color:#F0F0F0">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
 <td style="font-weight: bold; text-align:right">40,138,560</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">167,642                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">39,970,918</span></td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">612,013</td>
 <td style="font-weight: bold; text-align:right">2,556</td>
 <td style="font-weight: bold; text-align:right">271,490,188</td>
 <td style="font-weight: bold; text-align:right">4,139,547</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,584,518</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>391</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>
 <td style="font-weight: bold; text-align:right">38,808,771</td>
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+998</td>
 <td style="font-weight: bold; text-align:right;">181,845                                </td>
 <td style="font-weight: bold;
                                     text-align:right;background-color:red; color:white">+43</td>
 <td style="font-weight: bold; text-align:right">38,240,600</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">386,326</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">462,650</td>
 <td style="font-weight: bold; text-align:right">2,168</td>
 <td style="font-weight: bold; text-align:right">122,332,384</td>
 <td style="font-weight: bold; text-align:right">1,458,359</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">83,883,596</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>461</td><td>1</td>
 <td style="font-weight: bold; text-align:right">12</td>
 <td style="font-weight: bold; text-align:right">0.5</td>
 <td style="font-weight: bold; text-align:right">4,606</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
 <td style="font-weight: bold; text-align:right">38,303,320</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">709,195                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">36,249,161</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">1,344,964</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">177,862</td>
 <td style="font-weight: bold; text-align:right">3,293</td>
 <td style="font-weight: bold; text-align:right">63,776,166</td>
 <td style="font-weight: bold; text-align:right">296,146</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">215,353,593</a> </td>
 <td data-continent="South America" style="display:none">South America</td>
 <!-- 1 Case/Death/Test every X -->
 <td>6</td><td>304</td><td>3</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">6,245</td>
 </tr>,
 <tr style="background-color:#F0F0F0">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/south-korea/">S. Korea</a></td>
 <td style="font-weight: bold; text-align:right">34,571,873</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">35,934                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">34,535,939</span></td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">673,523</td>
 <td style="font-weight: bold; text-align:right">700</td>
 <td style="font-weight: bold; text-align:right">15,804,065</td>
 <td style="font-weight: bold; text-align:right">307,892</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/south-korea-population/">51,329,899</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <!-- 1 Case/Death/Test every X -->
 <td>1</td><td>1,428</td><td>3</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/japan/">Japan</a></td>
 <td style="font-weight: bold; text-align:right">33,803,572</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">74,694                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right;">N/A</td>
 <td style="text-align:right;font-weight:bold;">N/A</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">269,169</td>
 <td style="font-weight: bold; text-align:right">595</td>
 <td style="font-weight: bold; text-align:right">100,414,883</td>
 <td style="font-weight: bold; text-align:right">799,578</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/japan-population/">125,584,838</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <!-- 1 Case/Death/Test every X -->
 <td>4</td><td>1,681</td><td>1</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">95,582</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
 <td style="font-weight: bold; text-align:right">26,707,734</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">195,955                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">26,325,082</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">186,697</td>
 <td style="font-weight: bold; text-align:right">121</td>
 <td style="font-weight: bold; text-align:right">443,188</td>
 <td style="font-weight: bold; text-align:right">3,252</td>
 <td style="font-weight: bold; text-align:right">279,808,405</td>
 <td style="font-weight: bold; text-align:right">4,643,139</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,262,770</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>308</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">3,098</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
 <td style="font-weight: bold; text-align:right">24,885,790</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">232,112                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">24,632,758</span></td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">20,920</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">363,307</td>
 <td style="font-weight: bold; text-align:right">3,389</td>
 <td style="font-weight: bold; text-align:right">522,526,476</td>
 <td style="font-weight: bold; text-align:right">7,628,357</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">68,497,907</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>3</td><td>295</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">305</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
 <td style="font-weight: bold; text-align:right">23,875,738</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">401,945                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">23,294,406</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">179,387</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">163,750</td>
 <td style="font-weight: bold; text-align:right">2,757</td>
 <td style="font-weight: bold; text-align:right">273,400,000</td>
 <td style="font-weight: bold; text-align:right">1,875,095</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">145,805,947</a> </td>

In [27]:
totRows = []
for rows in tab1:
#     row = tab1.findALl("tr")[0]
    totRows.append(rows)

In [28]:
len(totRows)

744

In [29]:
totRows[711]

<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">207</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/liberia/">Liberia</a></td>
<td style="font-weight: bold; text-align:right">8,090</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">295                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">7,783</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">12</td>
<td style="font-weight: bold; text-align:right">2</td>
<td style="font-weight: bold; text-align:right">1,525</td>
<td style="font-weight: bold; text-align:right">56</td>
<td style="font-weight: bold; text-align:right">139,824</td>
<td style="font-weight: bold; text-align:right">26,356</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/liberia-population/">5,305,117</a> </td>
<td data-continent="Africa" style="display:none">Africa</td>
<!-- 1 Case/Death/Test every X -->
<td>656</td><td>17,983</td><td>38</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">2</td>
</tr>

In [30]:
country=[]
totalCases =[]
totalDeaths =[]

for row in tab1[9:232]: 
    try:
        col1= row.findAll("td")[1]      
        if col1 != None:
            country.append(col1)
#     print(col1.get_text())
        col2= row.findAll("td")[2]
        if col2 != None:
            totalCases.append(col2)
#     print(col2.get_text())
        col3= row.findAll("td")[4]
        if col3 != None:
            totalDeaths.append(col3)
#     print(col3.get_text())
   
    except:
        pass

In [31]:
len(country)

223

In [32]:
len(totalCases)

223

In [33]:
len(totalDeaths)

223

In [34]:
data=[]
for c, tc, td  in zip(country, totalCases, totalDeaths ):
    data.append([c.text, tc.text, td.text])
    print(c.text, tc.text, td.text)

USA 110,818,155 1,194,100
India 45,025,605 533,448
France 40,138,560 167,642
Germany 38,808,771 181,845
Brazil 38,303,320 709,195
S. Korea 34,571,873 35,934
Japan 33,803,572 74,694
Italy 26,707,734 195,955
UK 24,885,790 232,112
Russia 23,875,738 401,945
Turkey 17,232,066 102,174
Spain 13,914,811 121,760
Australia 11,754,909 24,073
Vietnam 11,624,114 43,206
Taiwan 10,241,523 19,005
Argentina 10,081,076 130,699
Netherlands 8,633,235 22,992
Mexico 7,702,809 334,958
Iran 7,625,812 146,767
Indonesia 6,826,664 161,954
Poland 6,654,829 120,487
Colombia 6,390,565 143,138
Greece 6,101,379 37,869
Austria 6,081,287 22,542
Portugal 5,641,679 28,060
Ukraine 5,557,995 112,418
Chile 5,345,980 64,497
Malaysia 5,269,967 37,340
Canada 4,915,977 57,905
Belgium 4,856,459 34,376
Israel 4,841,772 12,707
DPRK 4,772,813 74
Thailand 4,765,003 34,547
Czechia 4,756,789 43,482
Peru 4,568,225 222,161
Switzerland 4,449,493 14,452
Philippines 4,140,383 66,864
South Africa 4,076,463 102,595
Romania 3,521,283 68,822
Denmark 3,183,756 8,814
Singapore 2,994,295 1,933
Hong Kong 2,926,873 14,464
Sweden 2,752,056 27,142
Serbia 2,612,780 18,057
New Zealand 2,574,813 5,452
Iraq 2,465,545 25,375
Hungary 2,229,267 49,013
Bangladesh 2,047,199 29,482
Slovakia 1,876,826 21,212
Georgia 1,855,289 17,132
Jordan 1,746,997 14,122
Ireland 1,732,701 9,474
Pakistan 1,581,936 30,664
Finland 1,514,669 11,935
Norway 1,509,374 5,732
Kazakhstan 1,411,831 13,848
Lithuania 1,394,124 9,889
Slovenia 1,356,189 7,100
Bulgaria 1,338,621 38,731
Croatia 1,309,728 18,687
Guatemala 1,284,003 20,278
Morocco 1,278,512 16,301
Lebanon 1,243,838 10,952
Costa Rica 1,238,883 9,428
Bolivia 1,211,716 22,407
Tunisia 1,153,361 29,423
Cuba 1,115,210 8,530
Ecuador 1,070,188 36,043
UAE 1,067,030 2,349
Panama 1,058,933 8,688
Uruguay 1,041,111 7,664
Mongolia 1,011,451 2,284
Nepal 1,003,450 12,031
Belarus 994,037 7,118
Latvia 982,075 6,653
Saudi Arabia 841,469 9,646
Azerbaijan 834,371 10,379
Paraguay 831,154 20,132
Bahrain 729,549 1,574
Cyprus 681,110 1,365
Dominican Republic 674,608 4,384
Sri Lanka 672,745 16,896
Kuwait 666,756 2,570
Myanmar 641,687 19,495
Moldova 633,184 12,190
Estonia 627,452 3,001
Palestine 621,008 5,404
Venezuela 552,695 5,856
Egypt 516,023 24,613
Qatar 514,524 690
Libya 507,274 6,437
Ethiopia 501,117 7,574
RÃ©union 494,595 921
Honduras 474,590 11,165
Armenia 451,426 8,776
Bosnia and Herzegovina 403,558 16,382
Oman 399,449 4,628
Luxembourg 390,615 1,232
North Macedonia 350,244 9,963
Zambia 349,304 4,069
Kenya 344,130 5,689
Brunei  338,569 225
Albania 334,818 3,605
Botswana 330,442 2,801
Montenegro 296,386 2,845
Algeria 272,010 6,881
Nigeria 267,173 3,155
Zimbabwe 266,257 5,737
Uzbekistan 253,662 1,637
Mozambique 233,731 2,250
Afghanistan 231,010 7,980
Martinique 230,354 1,102
Laos 218,916 758
Iceland 209,870 229
Kyrgyzstan 206,897 2,991
Guadeloupe 203,235 1,021
El Salvador 201,855 4,230
Trinidad and Tobago 191,496 4,390
Maldives 186,694 316
Namibia 172,256 4,103
Uganda 171,983 3,632
Ghana 171,889 1,462
Jamaica 156,739 3,739
Cambodia 139,085 3,056
Rwanda 133,518 1,468
Cameroon 125,248 1,974
Malta 121,334 882
Barbados 110,480 648
Angola 107,271 1,937
Channel Islands 101,717 228
DRC 99,338 1,468
French Guiana 98,041 420
Malawi 89,168 2,686
Senegal 89,053 1,971
Ivory Coast 88,384 835
Suriname 82,588 1,408
New Caledonia 80,064 314
French Polynesia 79,254 650
Eswatini 75,191 1,427
Guyana 74,137 1,300
Belize 71,373 688
Fiji 69,117 885
Madagascar 68,486 1,426
Cabo Verde 64,477 417
Sudan 63,993 5,046
Mauritania 63,808 997
Bhutan 62,697 21
Syria 57,743 3,165
Burundi 54,721 38
Seychelles 51,220 172
Gabon 49,051 307
Andorra 48,015 165
Papua New Guinea 46,864 670
CuraÃ§ao 45,986 295
Aruba 44,224 292
Tanzania 43,223 846
Mauritius 43,025 1,051
Mayotte 42,027 188
Togo 39,553 290
Guinea 38,572 468
Bahamas 38,084 844
Isle of Man 38,008 116
Lesotho 36,135 723
Faeroe Islands 34,658 28
Haiti 34,542 860
Mali 33,164 743
Cayman Islands 31,472 37
Saint Lucia 30,209 410
Benin 28,036 163
Somalia 27,334 1,361
Micronesia 26,547 65
San Marino 26,185 128
Solomon Islands 25,954 199
Congo 25,375 386
Timor-Leste 23,460 138
Burkina Faso 22,109 400
Liechtenstein 21,571 94
Macao 21,395 123
Gibraltar 20,550 113
Grenada 19,693 238
Bermuda 18,860 165
South Sudan 18,819 147
Nicaragua 18,491 225
Tajikistan 17,786 125
Equatorial Guinea 17,229 183
Monaco 17,181 67
Samoa 17,006 31
Tonga 16,950 13
Marshall Islands 16,138 17
Dominica 16,038 74
Djibouti 15,690 189
CAR 15,440 113
Gambia 12,626 372
Saint Martin 12,324 63
Vanuatu 12,019 14
Greenland 11,971 21
Yemen 11,945 2,159
Caribbean Netherlands 11,682 38
Sint Maarten 11,051 92
Eritrea 10,189 103
Niger 9,931 312
St. Vincent Grenadines 9,674 124
Guinea-Bissau 9,614 177
Comoros 9,109 161
Antigua and Barbuda 9,106 146
Liberia 8,090 295
Sierra Leone 7,779 126
Chad 7,701 194
British Virgin Islands 7,392 64
Cook Islands 7,203 2
Sao Tome and Principe 6,751 80
Turks and Caicos 6,733 40
Saint Kitts and Nevis 6,607 48
Palau 6,270 10
St. Barth 5,507 6
Nauru 5,393 1
Kiribati 5,085 24
Anguilla 3,904 12
Wallis and Futuna 3,550 8
Saint Pierre Miquelon 3,452 2
Tuvalu 2,943 1
Saint Helena 2,166
Falkland Islands 1,930

In [35]:
data

[['USA', '110,818,155', '1,194,100                                '],
 ['India', '45,025,605', '533,448                                '],
 ['France', '40,138,560', '167,642                                '],
 ['Germany', '38,808,771', '181,845                                '],
 ['Brazil', '38,303,320', '709,195                                '],
 ['S. Korea', '34,571,873', '35,934                                '],
 ['Japan', '33,803,572', '74,694                                '],
 ['Italy', '26,707,734', '195,955                                '],
 ['UK', '24,885,790', '232,112                                '],
 ['Russia', '23,875,738', '401,945                                '],
 ['Turkey', '17,232,066', '102,174                                '],
 ['Spain', '13,914,811', '121,760                                '],
 ['Australia', '11,754,909', '24,073                                '],
 ['Vietnam', '11,624,114', '43,206                                '],
 ['Taiwan', '10,241,523', '19,005                                '],
 ['Argentina', '10,081,076', '130,699                                '],
 ['Netherlands', '8,633,235', '22,992                                '],
 ['Mexico', '7,702,809', '334,958                                '],
 ['Iran', '7,625,812', '146,767                                '],
 ['Indonesia', '6,826,664', '161,954                                '],
 ['Poland', '6,654,829', '120,487                                '],
 ['Colombia', '6,390,565', '143,138                                '],
 ['Greece', '6,101,379', '37,869                                '],
 ['Austria', '6,081,287', '22,542                                '],
 ['Portugal', '5,641,679', '28,060                                '],
 ['Ukraine', '5,557,995', '112,418                                '],
 ['Chile', '5,345,980', '64,497                                '],
 ['Malaysia', '5,269,967', '37,340                                '],
 ['Canada', '4,915,977', '57,905                                '],
 ['Belgium', '4,856,459', '34,376                                '],
 ['Israel', '4,841,772', '12,707                                '],
 ['DPRK', '4,772,813', '74                                '],
 ['Thailand', '4,765,003', '34,547                                '],
 ['Czechia', '4,756,789', '43,482                                '],
 ['Peru', '4,568,225', '222,161                                '],
 ['Switzerland', '4,449,493', '14,452                                '],
 ['Philippines', '4,140,383', '66,864                                '],
 ['South Africa', '4,076,463', '102,595                                '],
 ['Romania', '3,521,283', '68,822                                '],
 ['Denmark', '3,183,756', '8,814                                '],
 ['Singapore', '2,994,295', '1,933                                '],
 ['Hong Kong', '2,926,873', '14,464                                '],
 ['Sweden', '2,752,056', '27,142                                '],
 ['Serbia', '2,612,780', '18,057                                '],
 ['New Zealand', '2,574,813', '5,452                                '],
 ['Iraq', '2,465,545', '25,375                                '],
 ['Hungary', '2,229,267', '49,013                                '],
 ['Bangladesh', '2,047,199', '29,482                                '],
 ['Slovakia', '1,876,826', '21,212                                '],
 ['Georgia', '1,855,289', '17,132                                '],
 ['Jordan', '1,746,997', '14,122                                '],
 ['Ireland', '1,732,701', '9,474                                '],
 ['Pakistan', '1,581,936', '30,664                                '],
 ['Finland', '1,514,669', '11,935                                '],
 ['Norway', '1,509,374', '5,732                                '],
 ['Kazakhstan', '1,411,831', '13,848                                '],
 ['Lithuania', '1,394,124', '9,889                                '],
 ['Slovenia', '1,356,189', '7,100                                '],
 ['Bulgaria', '1,338,621', '38,731                                '],
 ['Croatia', '1,309,728', '18,687                                '],
 ['Guatemala', '1,284,003', '20,278                                '],
 ['Morocco', '1,278,512', '16,301                                '],
 ['Lebanon', '1,243,838', '10,952                                '],
 ['Costa Rica', '1,238,883', '9,428                                '],
 ['Bolivia', '1,211,716', '22,407                                '],
 ['Tunisia', '1,153,361', '29,423                                '],
 ['Cuba', '1,115,210', '8,530                                '],
 ['Ecuador', '1,070,188', '36,043                                '],
 ['UAE', '1,067,030', '2,349                                '],
 ['Panama', '1,058,933', '8,688                                '],
 ['Uruguay', '1,041,111', '7,664                                '],
 ['Mongolia', '1,011,451', '2,284                                '],
 ['Nepal', '1,003,450', '12,031                                '],
 ['Belarus', '994,037', '7,118                                '],
 ['Latvia', '982,075', '6,653                                '],
 ['Saudi Arabia', '841,469', '9,646                                '],
 ['Azerbaijan', '834,371', '10,379                                '],
 ['Paraguay', '831,154', '20,132                                '],
 ['Bahrain', '729,549', '1,574                                '],
 ['Cyprus', '681,110', '1,365                                '],
 ['Dominican Republic', '674,608', '4,384                                '],
 ['Sri Lanka', '672,745', '16,896                                '],
 ['Kuwait', '666,756', '2,570                                '],
 ['Myanmar', '641,687', '19,495                                '],
 ['Moldova', '633,184', '12,190                                '],
 ['Estonia', '627,452', '3,001                                '],
 ['Palestine', '621,008', '5,404                                '],
 ['Venezuela', '552,695', '5,856                                '],
 ['Egypt', '516,023', '24,613                                '],
 ['Qatar', '514,524', '690                                '],
 ['Libya', '507,274', '6,437                                '],
 ['Ethiopia', '501,117', '7,574                                '],
 ['RÃ©union', '494,595', '921                                '],
 ['Honduras', '474,590', '11,165                                '],
 ['Armenia', '451,426', '8,776                                '],
 ['Bosnia and Herzegovina',
  '403,558',
  '16,382                                '],
 ['Oman', '399,449', '4,628                                '],
 ['Luxembourg', '390,615', '1,232                                '],
 ['North Macedonia', '350,244', '9,963                                '],
 ['Zambia', '349,304', '4,069                                '],
 ['Kenya', '344,130', '5,689                                '],
 ['Brunei ', '338,569', '225                                '],
 ['Albania', '334,818', '3,605                                '],
 ['Botswana', '330,442', '2,801                                '],
 ['Montenegro', '296,386', '2,845                                '],
 ['Algeria', '272,010', '6,881                                '],
 ['Nigeria', '267,173', '3,155                                '],
 ['Zimbabwe', '266,257', '5,737                                '],
 ['Uzbekistan', '253,662', '1,637                                '],
 ['Mozambique', '233,731', '2,250                                '],
 ['Afghanistan', '231,010', '7,980                                '],
 ['Martinique', '230,354', '1,102                                '],
 ['Laos', '218,916', '758                                '],
 ['Iceland', '209,870', '229                                '],
 ['Kyrgyzstan', '206,897', '2,991                                '],
 ['Guadeloupe', '203,235', '1,021                                '],
 ['El Salvador', '201,855', '4,230                                '],
 ['Trinidad and Tobago', '191,496', '4,390                                '],
 ['Maldives', '186,694', '316                                '],
 ['Namibia', '172,256', '4,103                                '],
 ['Uganda', '171,983', '3,632                                '],
 ['Ghana', '171,889', '1,462                                '],
 ['Jamaica', '156,739', '3,739                                '],
 ['Cambodia', '139,085', '3,056                                '],
 ['Rwanda', '133,518', '1,468                                '],
 ['Cameroon', '125,248', '1,974                                '],
 ['Malta', '121,334', '882                                '],
 ['Barbados', '110,480', '648                                '],
 ['Angola', '107,271', '1,937                                '],
 ['Channel Islands', '101,717', '228                                '],
 ['DRC', '99,338', '1,468                                '],
 ['French Guiana', '98,041', '420                                '],
 ['Malawi', '89,168', '2,686                                '],
 ['Senegal', '89,053', '1,971                                '],
 ['Ivory Coast', '88,384', '835                                '],
 ['Suriname', '82,588', '1,408                                '],
 ['New Caledonia', '80,064', '314                                '],
 ['French Polynesia', '79,254', '650                                '],
 ['Eswatini', '75,191', '1,427                                '],
 ['Guyana', '74,137', '1,300                                '],
 ['Belize', '71,373', '688                                '],
 ['Fiji', '69,117', '885                                '],
 ['Madagascar', '68,486', '1,426                                '],
 ['Cabo Verde', '64,477', '417                                '],
 ['Sudan', '63,993', '5,046                                '],
 ['Mauritania', '63,808', '997                                '],
 ['Bhutan', '62,697', '21                                '],
 ['Syria', '57,743', '3,165                                '],
 ['Burundi', '54,721', '38                                '],
 ['Seychelles', '51,220', '172                                '],
 ['Gabon', '49,051', '307                                '],
 ['Andorra', '48,015', '165                                '],
 ['Papua New Guinea', '46,864', '670                                '],
 ['CuraÃ§ao', '45,986', '295                                '],
 ['Aruba', '44,224', '292                                '],
 ['Tanzania', '43,223', '846                                '],
 ['Mauritius', '43,025', '1,051                                '],
 ['Mayotte', '42,027', '188                                '],
 ['Togo', '39,553', '290                                '],
 ['Guinea', '38,572', '468                                '],
 ['Bahamas', '38,084', '844                                '],
 ['Isle of Man', '38,008', '116                                '],
 ['Lesotho', '36,135', '723                                '],
 ['Faeroe Islands', '34,658', '28                                '],
 ['Haiti', '34,542', '860                                '],
 ['Mali', '33,164', '743                                '],
 ['Cayman Islands', '31,472', '37                                '],
 ['Saint Lucia', '30,209', '410                                '],
 ['Benin', '28,036', '163                                '],
 ['Somalia', '27,334', '1,361                                '],
 ['Micronesia', '26,547', '65                                '],
 ['San Marino', '26,185', '128                                '],
 ['Solomon Islands', '25,954', '199                                '],
 ['Congo', '25,375', '386                                '],
 ['Timor-Leste', '23,460', '138                                '],
 ['Burkina Faso', '22,109', '400                                '],
 ['Liechtenstein', '21,571', '94                                '],
 ['Macao', '21,395', '123                                '],
 ['Gibraltar', '20,550', '113                                '],
 ['Grenada', '19,693', '238                                '],
 ['Bermuda', '18,860', '165                                '],
 ['South Sudan', '18,819', '147                                '],
 ['Nicaragua', '18,491', '225                                '],
 ['Tajikistan', '17,786', '125                                '],
 ['Equatorial Guinea', '17,229', '183                                '],
 ['Monaco', '17,181', '67                                '],
 ['Samoa', '17,006', '31                                '],
 ['Tonga', '16,950', '13                                '],
 ['Marshall Islands', '16,138', '17                                '],
 ['Dominica', '16,038', '74                                '],
 ['Djibouti', '15,690', '189                                '],
 ['CAR', '15,440', '113                                '],
 ['Gambia', '12,626', '372                                '],
 ['Saint Martin', '12,324', '63                                '],
 ['Vanuatu', '12,019', '14                                '],
 ['Greenland', '11,971', '21                                '],
 ['Yemen', '11,945', '2,159                                '],
 ['Caribbean Netherlands', '11,682', '38                                '],
 ['Sint Maarten', '11,051', '92                                '],
 ['Eritrea', '10,189', '103                                '],
 ['Niger', '9,931', '312                                '],
 ['St. Vincent Grenadines', '9,674', '124                                '],
 ['Guinea-Bissau', '9,614', '177                                '],
 ['Comoros', '9,109', '161                                '],
 ['Antigua and Barbuda', '9,106', '146                                '],
 ['Liberia', '8,090', '295                                '],
 ['Sierra Leone', '7,779', '126                                '],
 ['Chad', '7,701', '194                                '],
 ['British Virgin Islands', '7,392', '64                                '],
 ['Cook Islands', '7,203', '2                                '],
 ['Sao Tome and Principe', '6,751', '80                                '],
 ['Turks and Caicos', '6,733', '40                                '],
 ['Saint Kitts and Nevis', '6,607', '48                                '],
 ['Palau', '6,270', '10                                '],
 ['St. Barth', '5,507', '6                                '],
 ['Nauru', '5,393', '1                                '],
 ['Kiribati', '5,085', '24                                '],
 ['Anguilla', '3,904', '12                                '],
 ['Wallis and Futuna', '3,550', '8                                '],
 ['Saint Pierre Miquelon', '3,452', '2                                '],
 ['Tuvalu', '2,943', '1                                '],
 ['Saint Helena', '2,166', ' '],
 ['Falkland Islands', '1,930', ' ']]

In [36]:
import csv
with open('cvCases.csv','w') as f:
    writer = csv.writer(f)
    writer.writerows(data)

# JSON parsing

In [37]:
import json

In [38]:
wiki = requests.get("https://en.wikipedia.org/wiki/Main_Page")

In [39]:
wikisoup = BeautifulSoup(wiki.text)

In [40]:
wikisoup

<!DOCTYPE html>

<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-sticky-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-0 vector-feature-client-preferences-disabled vector-feature-client-prefs-pinned-disabled vector-toc-not-available" dir="ltr" lang="en">
<head>
<meta charset="utf-8"/>
<title>Wikipedia, the free encyclopedia</title>
<script>(function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-sticky-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-0 vector-feature-client-preferences-disabled vector-feature-client-prefs-pinned-disabled vector-toc-not-available";var cookie=document.cookie.match(/(?:^|; )enwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split('%2C').forEach(function(pref){className=className.replace(new RegExp('(^| )'+pref.replace(/-clientpref-\w+$|[^\w-]+/g,'')+'-clientpref-\\w+( |$)'),'$1'+pref+'$2');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":
["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"7c15accd-9e21-4d0d-adfa-60a12ddf67c4","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Main_Page","wgTitle":"Main Page","wgCurRevisionId":1189617895,"wgRevisionId":1189617895,"wgArticleId":15580374,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"Main_Page","wgRelevantArticleId":15580374,"wgIsProbablyEditable":false,"wgRelevantPageIsProbablyEditable":false,"wgRestrictionEdit":["sysop"],"wgRestrictionMove":["sysop"],"wgIsMainPage":true,"wgNoticeProject":"wikipedia","wgFlaggedRevsParams":{"tags":{"status":{"levels":1}}},"wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgPopupsFlags":6,"wgVisualEditor":{"pageLanguageCode":
"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":3000,"wgULSCurrentAutonym":"English","wgCentralAuthMobileDomain":false,"wgEditSubmitButtonLabelPublish":true,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgWikibaseItemId":"Q5296","wgCheckUserClientHintsHeadersJsApi":["architecture","bitness","brands","fullVersionList","mobile","model","platform","platformVersion"],"GEHomepageSuggestedEditsEnableTopics":true,"wgGETopicsMatchModeEnabled":false,"wgGEStructuredTaskRejectionReasonTextInputEnabled":false,"wgGELevelingUpEnabledForUser":false};RLSTATE={"skins.vector.user.styles":"ready","ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","skins.vector.user":"ready","ext.globalCssJs.user":"ready","user":
"ready","user.options":"loading","codex-search-styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","ext.wikimediaBadges":"ready"};RLPAGEMODULES=["mediawiki.toggleAllCollapsibles","site","mediawiki.page.ready","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ReferenceTooltips","ext.gadget.switcher","ext.urlShortener.toolbar","ext.centralauth.centralautologin","mmv.head","mmv.bootstrap.autostart","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.visualEditor.targetLoader","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","wikibase.client.vector-2022","ext.checkUser.clientHints","ext.growthExperiments.SuggestedEditSession"];</script>
<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});
}];});});</script>
<link href="/w/load.php?lang=en&amp;modules=codex-search-styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediaBadges%7Cskins.vector.icons%2Cstyles&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022"></script>
<meta content="" name="ResourceLoaderDynamicStyles"/>
<link href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<meta content="MediaWiki 1.42.0-wmf.15" name="generator"/>
<meta content="origin" name="referrer"/>
<meta content="origin-when-cross-origin" name="referrer"/>
<meta content="max-image-preview:standard" name="robots"/>
<meta content="telephone=no" name="format-detection"/>
<meta content="https://upload.wikimedia.org/wikipedia/commons/5/53/Jardin_du_Musee_Rodin_Paris_Le_Penseur_20050402_%2802%29.jpg" property="og:image"/>
<meta content="1200" property="og:image:width"/>
<meta content="1600" property="og:image:height"/>
<meta content="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Jardin_du_Musee_Rodin_Paris_Le_Penseur_20050402_%2802%29.jpg/800px-Jardin_du_Musee_Rodin_Paris_Le_Penseur_20050402_%2802%29.jpg" property="og:image"/>
<meta content="800" property="og:image:width"/>
<meta content="1067" property="og:image:height"/>
<meta content="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Jardin_du_Musee_Rodin_Paris_Le_Penseur_20050402_%2802%29.jpg/640px-Jardin_du_Musee_Rodin_Paris_Le_Penseur_20050402_%2802%29.jpg" property="og:image"/>
<meta content="640" property="og:image:width"/>
<meta content="853" property="og:image:height"/>
<meta content="width=1000" name="viewport"/>
<meta content="Wikipedia, the free encyclopedia" property="og:title"/>
<meta content="website" property="og:type"/>
<link href="//upload.wikimedia.org" rel="preconnect"/>
<link href="//en.m.wikipedia.org/wiki/Main_Page" media="only screen and (max-width: 720px)" rel="alternate"/>
<link href="/w/api.php?action=featuredfeed&amp;feed=potd&amp;feedformat=atom" rel="alternate" title="Wikipedia picture of the day feed" type="application/atom+xml"/>
<link href="/w/api.php?action=featuredfeed&amp;feed=featured&amp;feedformat=atom" rel="alternate" title="Wikipedia featured articles feed" type="application/atom+xml"/>
<link href="/w/api.php?action=featuredfeed&amp;feed=onthisday&amp;feedformat=atom" rel="alternate" title='Wikipedia "On this day..." feed' type="application/atom+xml"/>
<link href="/static/apple-touch/wikipedia.png" rel="apple-touch-icon"/>
<link href="/static/favicon/wikipedia.ico" rel="icon"/>
<link href="/w/opensearch_desc.php" rel="search" title="Wikipedia (en)" type="application/opensearchdescription+xml"/>
<link href="//en.wikipedia.org/w/api.php?action=rsd" rel="EditURI" type="application/rsd+xml"/>
<link href="https://en.wikipedia.org/wiki/Main_Page" rel="canonical"/>
<link href="https://creativecommons.org/licenses/by-sa/4.0/deed.en" rel="license"/>
<link href="/w/index.php?title=Special:RecentChanges&amp;feed=atom" rel="alternate" title="Wikipedia Atom feed" type="application/atom+xml"/>
<link href="//meta.wikimedia.org" rel="dns-prefetch">
<link href="//login.wikimedia.org" rel="dns-prefetch"/>
</link></head>
<body class="skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject page-Main_Page rootpage-Main_Page skin-vector-2022 action-view"><a class="mw-jump-link" href="#bodyContent">Jump to content</a>
<div class="vector-header-container">
<header class="vector-header mw-header">
<div class="vector-header-start">
<nav aria-label="Site" class="vector-main-menu-landmark" role="navigation">
<div class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right" id="vector-main-menu-dropdown">
<input aria-haspopup="true" aria-label="Main menu" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-main-menu-dropdown" id="vector-main-menu-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-main-menu-dropdown-checkbox" id="vector-main-menu-dropdown-label"><span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu"></span>
<span class="vector-dropdown-label-text">Main menu</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-main-menu-unpinned-container">
<div class="vector-main-menu vector-pinnable-element" id="vector-main-menu">
<div class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned" data-feature-name="main-menu-pinned" data-pinnable-element-id="vector-main-menu" data-pinned-container-id="vector-main-menu-pinned-container" data-unpinned-container-id="vector-main-menu-unpinned-container">
<div class="vector-pinnable-header-label">Main menu</div>
<button class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">move to sidebar</button>
<button class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">hide</button>
</div>
<div class="vector-menu mw-portlet mw-portlet-navigation" id="p-navigation">
<div class="vector-menu-heading">
		Navigation
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-mainpage-description"><a accesskey="z" href="/wiki/Main_Page" title="Visit the main page [z]"><span>Main page</span></a></li><li class="mw-list-item" id="n-contents"><a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia"><span>Contents</span></a></li><li class="mw-list-item" id="n-currentevents"><a href="/wiki/Portal:Current_events" title="Articles related to current events"><span>Current events</span></a></li><li class="mw-list-item" id="n-randompage"><a accesskey="x" href="/wiki/Special:Random" title="Visit a randomly selected article [x]"><span>Random article</span></a></li><li class="mw-list-item" id="n-aboutsite"><a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works"><span>About Wikipedia</span></a></li><li class="mw-list-item" id="n-contactpage"><a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia"><span>Contact us</span></a></li><li class="mw-list-item" id="n-sitesupport"><a href="https://donate.wikimedia.org/wiki/Special:FundraiserRedirector?utm_source=donate&amp;utm_medium=sidebar&amp;utm_campaign=C13_en.wikipedia.org&amp;uselang=en" title="Support us by donating to the Wikimedia Foundation"><span>Donate</span></a></li>
</ul>
</div>
</div>
<div class="vector-menu mw-portlet mw-portlet-interaction" id="p-interaction">
<div class="vector-menu-heading">
		Contribute
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-help"><a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia"><span>Help</span></a></li><li class="mw-list-item" id="n-introduction"><a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia"><span>Learn to edit</span></a></li><li class="mw-list-item" id="n-portal"><a href="/wiki/Wikipedia:Community_portal" title="The hub for editors"><span>Community portal</span></a></li><li class="mw-list-item" id="n-recentchanges"><a accesskey="r" href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]"><span>Recent changes</span></a></li><li class="mw-list-item" id="n-upload"><a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia"><span>Upload file</span></a></li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div>
</nav>
<a class="mw-logo" href="/wiki/Main_Page">
<img alt="" aria-hidden="true" class="mw-logo-icon" height="50" src="/static/images/icons/wikipedia.png" width="50"/>
<span class="mw-logo-container">
<img alt="Wikipedia" class="mw-logo-wordmark" src="/static/images/mobile/copyright/wikipedia-wordmark-en.svg" style="width: 7.5em; height: 1.125em;"/>
<img alt="The Free Encyclopedia" class="mw-logo-tagline" height="13" src="/static/images/mobile/copyright/wikipedia-tagline-en.svg" style="width: 7.3125em; height: 0.8125em;" width="117"/>
</span>
</a>
</div>
<div class="vector-header-end">
<div class="vector-search-box-vue vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box" id="p-search" role="search">
<a accesskey="f" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" href="/wiki/Special:Search" id="" title="Search Wikipedia [f]"><span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search"></span>
<span>Search</span>
</a>
<div class="vector-typeahead-search-container">
<div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">
<form action="/w/index.php" class="cdx-search-input cdx-search-input--has-end-button" id="searchform">
<div class="cdx-search-input__input-wrapper" data-search-loc="header-moved" id="simpleSearch">
<div class="cdx-text-input cdx-text-input--has-start-icon">
<input accesskey="f" aria-label="Search Wikipedia" autocapitalize="sentences" class="cdx-text-input__input" id="searchInput" name="search" placeholder="Search Wikipedia" title="Search Wikipedia [f]" type="search"/>
<span class="cdx-text-input__icon cdx-text-input__start-icon"></span>
</div>
<input name="title" type="hidden" value="Special:Search"/>
</div>
<button class="cdx-button cdx-search-input__end-button">Search</button>
</form>
</div>
</div>
</div>
<nav aria-label="Personal tools" class="vector-user-links vector-user-links-wide" role="navigation">
<div class="vector-user-links-main">
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-preferences">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-userpage">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<nav aria-label="Appearance" class="vector-client-prefs-landmark">
</nav>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-notifications">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet" id="p-vector-user-menu-overflow">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-createaccount-2"><a class="" data-mw="interface" href="/w/index.php?title=Special:CreateAccount&amp;returnto=Main+Page" title="You are encouraged to create an account and log in; however, it is not mandatory"><span>Create account</span></a>
</li>
<li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-login-2"><a accesskey="o" class="" data-mw="interface" href="/w/index.php?title=Special:UserLogin&amp;returnto=Main+Page" title="You're encouraged to log in; however, it's not mandatory. [o]"><span>Log in</span></a>
</li>
</ul>
</div>
</div>
</div>
<div class="vector-dropdown vector-user-menu vector-button-flush-right vector-user-menu-logged-out" id="vector-user-links-dropdown" title="Log in and more options">
<input aria-haspopup="true" aria-label="Personal tools" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-user-links-dropdown" id="vector-user-links-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-user-links-dropdown-checkbox" id="vector-user-links-dropdown-label"><span class="vector-icon mw-ui-icon-ellipsis mw-ui-icon-wikimedia-ellipsis"></span>
<span class="vector-dropdown-label-text">Personal tools</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-menu mw-portlet mw-portlet-personal user-links-collapsible-item" id="p-personal" title="User menu">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="user-links-collapsible-item mw-list-item" id="pt-createaccount"><a href="/w/index.php?title=Special:CreateAccount&amp;returnto=Main+Page" title="You are encouraged to create an account and log in; however, it is not mandatory"><span class="vector-icon mw-ui-icon-userAdd mw-ui-icon-wikimedia-userAdd"></span> <span>Create account</span></a></li><li class="user-links-collapsible-item mw-list-item" id="pt-login"><a accesskey="o" href="/w/index.php?title=Special:UserLogin&amp;returnto=Main+Page" title="You're encouraged to log in; however, it's not mandatory. [o]"><span class="vector-icon mw-ui-icon-logIn mw-ui-icon-wikimedia-logIn"></span> <span>Log in</span></a></li>
</ul>
</div>
</div>
<div class="vector-menu mw-portlet mw-portlet-user-menu-anon-editor" id="p-user-menu-anon-editor">
<div class="vector-menu-heading">
		Pages for logged out editors <a aria-label="Learn more about editing" href="/wiki/Help:Introduction"><span>learn more</span></a>
</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="pt-anoncontribs"><a accesskey="y" href="/wiki/Special:MyContributions" title="A list of edits made from this IP address [y]"><span>Contributions</span></a></li><li class="mw-list-item" id="pt-anontalk"><a accesskey="n" href="/wiki/Special:MyTalk" title="Discussion about edits from this IP address [n]"><span>Talk</span></a></li>
</ul>
</div>
</div>
</div>
</div>
</nav>
</div>
</header>
</div>
<div class="mw-page-container">
<div class="mw-page-container-inner">
<div class="vector-sitenotice-container">
<div id="siteNotice"><!-- CentralNotice --></div>
</div>
<div class="vector-column-start">
<div class="vector-main-menu-container">
<div id="mw-navigation">
<nav aria-label="Site" class="vector-main-menu-landmark" id="mw-panel" role="navigation">
<div class="vector-pinned-container" id="vector-main-menu-pinned-container">
</div>
</nav>
</div>
</div>
</div>
<div class="mw-content-container">
<main class="mw-body" id="content" role="main">
<header class="mw-body-header vector-page-titlebar vector-page-titlebar-blank">
<h1 class="firstHeading mw-first-heading" id="firstHeading" style="display: none"><span class="mw-page-title-main">Main Page</span></h1>
<div class="mw-indicators">
</div>
</header>
<div class="vector-page-toolbar">
<div class="vector-page-toolbar-container">
<div id="left-navigation">
<nav aria-label="Namespaces">
<div class="vector-menu vector-menu-tabs mw-portlet mw-portlet-associated-pages" id="p-associated-pages">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">

In [41]:
wikiinfo = wikisoup.findAll(type="application/ld+json")

In [42]:
data = wikiinfo[0].contents[0]

In [43]:
data

'{"@context":"https:\\/\\/schema.org","@type":"Article","name":"Main Page","url":"https:\\/\\/en.wikipedia.org\\/wiki\\/Main_Page","sameAs":"http:\\/\\/www.wikidata.org\\/entity\\/Q5296","mainEntity":"http:\\/\\/www.wikidata.org\\/entity\\/Q5296","author":{"@type":"Organization","name":"Contributors to Wikimedia projects"},"publisher":{"@type":"Organization","name":"Wikimedia Foundation, Inc.","logo":{"@type":"ImageObject","url":"https:\\/\\/www.wikimedia.org\\/static\\/images\\/wmf-hor-googpub.png"}},"datePublished":"2002-01-26T15:28:12Z","dateModified":"2023-12-12T23:59:34Z","image":"https:\\/\\/upload.wikimedia.org\\/wikipedia\\/commons\\/5\\/53\\/Jardin_du_Musee_Rodin_Paris_Le_Penseur_20050402_%2802%29.jpg","headline":"Wikimedia project page"}'

In [44]:
jsondata = json.loads(data)

In [45]:
jsondata

{'@context': 'https://schema.org',
 '@type': 'Article',
 'name': 'Main Page',
 'url': 'https://en.wikipedia.org/wiki/Main_Page',
 'sameAs': 'http://www.wikidata.org/entity/Q5296',
 'mainEntity': 'http://www.wikidata.org/entity/Q5296',
 'author': {'@type': 'Organization',
  'name': 'Contributors to Wikimedia projects'},
 'publisher': {'@type': 'Organization',
  'name': 'Wikimedia Foundation, Inc.',
  'logo': {'@type': 'ImageObject',
   'url': 'https://www.wikimedia.org/static/images/wmf-hor-googpub.png'}},
 'datePublished': '2002-01-26T15:28:12Z',
 'dateModified': '2023-12-12T23:59:34Z',
 'image': 'https://upload.wikimedia.org/wikipedia/commons/5/53/Jardin_du_Musee_Rodin_Paris_Le_Penseur_20050402_%2802%29.jpg',
 'headline': 'Wikimedia project page'}

In [46]:
pageAddress = jsondata['url']

In [47]:
pageAddress

'https://en.wikipedia.org/wiki/Main_Page'

# Get files from cmsc320

In [48]:
r = requests.get("https://www.cs.umd.edu/class/spring2024/cmsc320-0201/")

In [49]:
root = BeautifulSoup(r.content)

In [50]:
links = root.findAll("a")

In [51]:
links

[<a class="navbar-brand js-scroll-trigger" href="#page-top">
 <span class="d-block d-lg-none">CMSC 320</span>
 <span class="d-none d-lg-block">
 <h6 style="color: #fff;">CMSC 320 - Spring 2024<br/>
 <h6 style="color: #fff;"> Sections: 0201 </h6>

 <img alt="" class="img-fluid img-profile rounded-circle mx-auto mb-2" src="img/logo1.png"/>
 </h6></span>
 </a>,
 <a class="nav-link js-scroll-trigger" href="#description">Description</a>,
 <a class="nav-link js-scroll-trigger" href="#schedule">Schedule</a>,
 <a class="nav-link js-scroll-trigger" href="#staff">Staff and Office hours</a>,
 <a class="nav-link js-scroll-trigger" href="#classresources">Class Resources</a>,
 <a href="syllabus/syllabus.pdf" style="color: white;">Syllabus</a>,
 <a href="https://hbr.org/2023/09/4-skills-the-next-generation-of-data-scientists-needs-to-develop" style="color: #2196F3;" target="_blank">Skills the next generation of data scientists need to know</a>,
 <a href="https://realpython.com/python-web-scraping-practical-introduction/" style="color: #2196F3;" target="_blank"> Webscraping Intro</a>,
 <a href="https://numpy.org/doc/stable/user/absolute_beginners.html" style="color: #2196F3;" target="_blank"> Numpy for beginners</a>,
 <a href="https://docs.jupyter.org/en/latest/running.html#running" style="color: #0D47A1;">Running Jupyter Notebook </a>,
 <a href="files/tutorial.pdf" style="color: #0D47A1;">Tutorial</a>,
 <a href="https://piazza.com/" style="color: #0D47A1;"> Piazza </a>,
 <a href="https://www.gradescope.com" style="color: #0D47A1;"> Gradescope</a>,
 <a href="https://elms.umd.edu" style="color: #0D47A1;"> ELMS</a>,
 <a class="university" href="http://www.umd.edu" title="University of Maryland website">University of Maryland website</a>,
 <a href="https://umd.edu/web-accessibility" title="UMD web accessibility statement">Web Accessibility</a>,
 <a class="facebook" href="https://www.facebook.com/UMDCompSci" target="_blank" title="Facebook">Facebook</a>,
 <a class="twitter" href="https://twitter.com/UMDCompSci" target="_blank" title="Twitter">Twitter</a>,
 <a class="linkedin" data-proofer-ignore="" href="https://www.linkedin.com/in/umd-cs-544a3b62" target="_blank" title="LinkedIn">LinkedIn</a>,
 <a class="rss" href="http://www.cs.umd.edu/feeds/news/all" target="_blank" title="RSS Feed">RSS Feed</a>]

In [52]:
text = "this is introduction to data science, cmsc320, specifically 320 fall 2021"

In [53]:
import re

In [54]:
match = re.search(r"cmsc320",text)
print(match.start())

38

In [55]:
match = re.match(r"cmsc320",text)

In [56]:
print(match)

None

In [57]:
for match in re.finditer(r"320", text):
    print( match.start() )

42
60

In [58]:
match = re.findall(r"cmsc320", text)
match

['cmsc320']